name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Lint
        if: ${{ always() }}
        run: pylint candystore tests
      - name: Check types
        if: ${{ always() }}
        run: mypy candystore tests
      - name: Check documentation
        if: ${{ always() }}
        run: pydocstyle candystore
      - name: Check formatting
        if: ${{ always() }}
        run: black candystore tests --check
      - name: Run tests
        if: ${{ always() }}
        run: pytest
